name: classy-prelude-conduit
version: '1.3.0'
synopsis: classy-prelude together with conduit functions
description: classy-prelude together with conduit functions
category: Control, Prelude
author: Michael Snoyman
maintainer: michael@snoyman.com
license: MIT
github: snoyberg/mono-traversable.git
extra-source-files:
- README.md
- ChangeLog.md
dependencies:
- transformers
- bytestring
library:
  ghc-options:
  - -Wall
  - -fno-warn-orphans
  exposed-modules:
  - ClassyPrelude.Conduit
  dependencies:
  - base >=4 && <5
  - conduit >=1.0 && <1.3
  - classy-prelude >=1.3.0 && <1.3.1
  - monad-control
  - resourcet
  - void
  - conduit-combinators >=0.2.8
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - hspec
    - classy-prelude-conduit
    - QuickCheck
    - conduit
