module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args:
- -Wall
- -Werror
- -hide-package=hashmap
excluded-modules:
- Setup.hs
- test/main.hs
