module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
modules:
  Main(classy-prelude/test/main.hs):
    filename: classy-prelude/test/main.hs
  Data.Sequences.Lazy:
    filename: classy-prelude/Data/Sequences/Lazy.hs
  Main(classy-prelude/Setup.hs):
    filename: classy-prelude/Setup.hs
  Main(classy-prelude-yesod/Setup.hs):
    filename: classy-prelude-yesod/Setup.hs
  Data.Textual.Encoding:
    filename: classy-prelude/Data/Textual/Encoding.hs
  ClassyPrelude.Classes:
    filename: classy-prelude/ClassyPrelude/Classes.hs
  Main(classy-prelude-conduit/Setup.hs):
    filename: classy-prelude-conduit/Setup.hs
  ClassyPrelude.Yesod:
    filename: classy-prelude-yesod/ClassyPrelude/Yesod.hs
  Main(classy-prelude-conduit/test/Spec.hs):
    filename: classy-prelude-conduit/test/Spec.hs
  ClassyPrelude.Conduit:
    filename: classy-prelude-conduit/ClassyPrelude/Conduit.hs
  ClassyPrelude:
    filename: classy-prelude/ClassyPrelude.hs
version: 1
extra-packages: ! 'Git: https://github.com/snoyberg/mono-traversable.git 8ecf2fe8fe303fb67693b8fb0f0e0e32f636c358'
ghc-args:
- -hide-package
- hashmap
