module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
modules: {}
version: 1
extra-packages: ''
ghc-args:
- -hide-package=hashmap
