resolver: lts-9.9
packages:
- minlen
- mono-traversable
- mono-traversable-instances
- chunked-data
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit-combinators
- mutable-containers
extra-deps:
- resourcet-1.2.0
- conduit-1.3.0
- conduit-extra-1.3.0
- typed-process-0.2.1.0
- unliftio-0.2.4.0
- unliftio-core-0.1.1.0
- http-conduit-2.3.0
