resolver: lts-6.4

extra-deps:
- basic-prelude-0.5.1
- safe-exceptions-0.1.0.0

packages:
  - 'classy-prelude'
  - 'classy-prelude-conduit'
  - 'classy-prelude-yesod'
  - location:
      git: https://github.com/snoyberg/mono-traversable
      commit: bcc5d232fc411f4ee97b2cea30d69a340996955f
    extra-dep: true
    subdirs:
    - mono-traversable
    - mono-traversable-instances
  - location:
      git: https://github.com/fpco/chunked-data
      commit: f553a114eac5e742b80c438ec05269523dd57873
    extra-dep: true
  - location:
      git: https://github.com/fpco/conduit-combinators
      commit: add9751e53e6dad56a160dfcb9fd54ff9a6acd95
    extra-dep: true
