resolver: lts-6.4
packages:
- minlen
- mono-traversable
- mono-traversable-instances
- chunked-data
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit-combinators
- mutable-containers
extra-deps:
- safe-exceptions-0.1.1.0
