resolver: lts-9.9
packages:
- minlen
- mono-traversable
- mono-traversable-instances
- chunked-data
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit-combinators
- mutable-containers
extra-deps:
#- conduit-extra-1.2.2
- typed-process-0.2.0.0
- unliftio-0.2.1.0
- ../conduit/resourcet
- ../conduit/conduit
- ../conduit/conduit-extra
