resolver: lts-6.4

extra-deps:
- basic-prelude-0.5.1
- safe-exceptions-0.1.0.0

packages:
  - 'classy-prelude'
  - 'classy-prelude-conduit'
  - 'classy-prelude-yesod'
  - location:
      git: https://github.com/snoyberg/mono-traversable
      commit: c5f0ef772ac8904b4f8c199e32afe1769779c020
    extra-dep: true
    subdirs:
    - mono-traversable
    - mono-traversable-instances
  - location:
      git: https://github.com/fpco/chunked-data
      commit: f553a114eac5e742b80c438ec05269523dd57873
    extra-dep: true
  - location:
      git: https://github.com/fpco/conduit-combinators
      commit: 3b88c85219a3b716415069314dbe73afbea3c392
    extra-dep: true

flags:
  mono-traversable:
    base49: false
