resolver: lts-6.14
packages:
- minlen
- mono-traversable
- mono-traversable-instances
- chunked-data
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit-combinators
- mutable-containers
extra-deps:
- safe-exceptions-0.1.4.0
- basic-prelude-0.5.2
- monad-unlift-0.2.0
