name: classy-prelude
version: '1.3.0'
synopsis: A typeclass-based Prelude.
description: ! 'Modern best practices without name collisions. No partial functions
  are exposed, but modern data structures are, without requiring import lists. Qualified
  modules also are not needed: instead operations are based on type-classes from the
  mono-traversable package.'
category: Control, Prelude
author: Michael Snoyman
maintainer: michael@snoyman.com
license: MIT
github: snoyberg/mono-traversable.git
extra-source-files:
- README.md
- ChangeLog.md
dependencies:
- transformers
- unordered-containers
library:
  ghc-options:
  - -Wall
  - -fno-warn-orphans
  exposed-modules:
  - ClassyPrelude
  dependencies:
  - base >=4 && <5
  - basic-prelude >=0.4 && <0.7
  - containers >=0.4.2
  - text
  - bytestring
  - vector
  - hashable
  - lifted-base >=0.2
  - lifted-async >=0.3
  - async
  - mono-traversable >=1.0
  - mono-traversable-instances
  - exceptions >=0.5
  - semigroups
  - vector-instances
  - time
  - time-locale-compat
  - chunked-data >=0.3
  - ghc-prim
  - stm
  - primitive
  - mtl
  - bifunctors
  - mutable-containers >=0.3 && <0.4
  - dlist >=0.7
  - transformers-base
  - safe-exceptions >=0.1.1
  - deepseq
  - monad-unlift >=0.2
  - say
  - stm-chans >=3
tests:
  test:
    main: main.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - classy-prelude
    - base
    - hspec >=1.3
    - QuickCheck
    - containers
