module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-unstable
cabal-file: project.cabal
hidden-packages: classy-prelude classy-prelude-conduit
version: 1
extra-packages: ! 'Local: chunked-data 1.0'
ghc-args: []
excluded-modules: []
