name:        conduit-combinators
version:     1.3.0
synopsis:    DEPRECATED Functionality merged into the conduit package itself
description: See docs and README at <http://www.stackage.org/package/conduit-combinators>
category:    Data, Conduit
author:      Michael Snoyman
maintainer:  michael@snoyman.com
license:     MIT
github:      snoyberg/mono-traversable

extra-source-files:
- ChangeLog.md
- README.md

dependencies:
- base >=4.9 && <5

library: {}
