name:        conduit-combinators
version:     1.2.0
synopsis:    Commonly used conduit functions, for both chunked and unchunked data
description: See docs and README at <http://www.stackage.org/package/conduit-combinators>
category:    Data, Conduit
author:      Michael Snoyman
maintainer:  michael@snoyman.com
license:     MIT
github:      snoyberg/mono-traversable

extra-source-files:
- test/subdir/dummyfile.txt
- fusion-macros.h
- ChangeLog.md
- README.md

dependencies:
- transformers
- vector
- text
- bytestring
- mwc-random
- base16-bytestring
- filepath
- unliftio-core
library:
  ghc-options:
  - -Wall
  - -O2
  source-dirs: src
  other-modules:
  - Data.Conduit.Combinators.Unqualified
  dependencies:
  - base >=4 && <5
  - chunked-data >=0.3
  - conduit >=1.2.8
  - conduit-extra >=1.2.2
  - mono-traversable >=1.0
  - primitive
  - unix-compat
  - base64-bytestring >=0.1.1.1
  - resourcet
  include-dirs: .
  when:
  - condition: os(windows)
    then:
      cpp-options: -DWINDOWS
    else:
      dependencies:
      - unix
  - condition: "!impl(ghc>=7.9)"
    dependencies:
    - void
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    cpp-options: -DTEST
    dependencies:
    - conduit-combinators
    - base
    - hspec >=1.3
    - chunked-data
    - mono-traversable
    - silently
    - base64-bytestring
    - mtl
    - conduit
    - containers
    - safe
    - QuickCheck >=2.5
    - directory
    when:
    - condition: os(windows)
      cpp-options: -DWINDOWS
